# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\elira\Desktop\python\PYQT5_NEW_UI\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_window(object):
    def setupUi(self, Main_window):
        Main_window.setObjectName("Main_window")
        Main_window.resize(545, 847)
        Main_window.setStyleSheet("background-color: rgba(254, 254, 254, 1);")
        self.centralwidget = QtWidgets.QWidget(Main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(150, 80, 251, 41))
        self.title.setStyleSheet("color: rgba(22, 25, 50, 1);\n"
"font-size: 28pt;")
        self.title.setObjectName("title")
        self.email_label = QtWidgets.QLabel(self.centralwidget)
        self.email_label.setGeometry(QtCore.QRect(110, 220, 51, 31))
        self.email_label.setStyleSheet("font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);")
        self.email_label.setObjectName("email_label")
        self.email_input = QtWidgets.QLineEdit(self.centralwidget)
        self.email_input.setGeometry(QtCore.QRect(110, 260, 331, 41))
        self.email_input.setStyleSheet("border-radius: 20px;\n"
"background-color:rgba(240, 240, 240, 1);\n"
"\n"
"font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);\n"
"\n"
"padding: 5px 10px;")
        self.email_input.setObjectName("email_input")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(110, 340, 91, 31))
        self.password_label.setStyleSheet("font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);")
        self.password_label.setObjectName("password_label")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(110, 380, 331, 41))
        self.password_input.setStyleSheet("border-radius: 20px;\n"
"background-color:rgba(240, 240, 240, 1);\n"
"\n"
"font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);\n"
"\n"
"padding: 5px 10px;")
        self.password_input.setObjectName("password_input")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(110, 470, 331, 41))
        self.submit_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #f20089, stop:0.5 #b100e8, stop:1 #6a00f4);\n"
"\n"
"border-radius: 20px;\n"
"font-size: 20px;\n"
"color: rgba(254, 254, 254, 1);")
        self.submit_button.setObjectName("submit_button")
        self.signup_button = QtWidgets.QPushButton(self.centralwidget)
        self.signup_button.setGeometry(QtCore.QRect(140, 760, 261, 51))
        self.signup_button.setStyleSheet("font-size:10pt;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #f20089, stop:0.5 #b100e8, stop:1 #6a00f4);\n"
"text-decoration: underline;\n"
"background: transparent\n"
"\n"
"")
        self.signup_button.setObjectName("signup_button")
        Main_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Main_window)
        self.statusbar.setObjectName("statusbar")
        Main_window.setStatusBar(self.statusbar)

        self.retranslateUi(Main_window)
        QtCore.QMetaObject.connectSlotsByName(Main_window)

    def retranslateUi(self, Main_window):
        _translate = QtCore.QCoreApplication.translate
        Main_window.setWindowTitle(_translate("Main_window", "MainWindow"))
        self.title.setText(_translate("Main_window", "Bull Dashboard"))
        self.email_label.setText(_translate("Main_window", "Email"))
        self.password_label.setText(_translate("Main_window", "password"))
        self.submit_button.setText(_translate("Main_window", "Log in"))
        self.signup_button.setText(_translate("Main_window", "Don\'t have an account? Crreate one here"))
