# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\elira\Desktop\python\PYQT5_NEW_UI\UI\Dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dashboard_window(object):
    def setupUi(self, Dashboard_window):
        Dashboard_window.setObjectName("Dashboard_window")
        Dashboard_window.resize(1388, 849)
        Dashboard_window.setStyleSheet("background-color: rgba(254, 254, 254, 1);")
        self.centralwidget = QtWidgets.QWidget(Dashboard_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 301, 811))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(620, 280, 321, 201))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: rgba(22, 25, 50, 1);\n"
"font-size: 28pt;")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setObjectName("label")
        Dashboard_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Dashboard_window)
        self.statusbar.setObjectName("statusbar")
        Dashboard_window.setStatusBar(self.statusbar)

        self.retranslateUi(Dashboard_window)
        QtCore.QMetaObject.connectSlotsByName(Dashboard_window)

    def retranslateUi(self, Dashboard_window):
        _translate = QtCore.QCoreApplication.translate
        Dashboard_window.setWindowTitle(_translate("Dashboard_window", "MainWindow"))
        self.label.setText(_translate("Dashboard_window", "Dashboard"))
