# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\eliran\Desktop\python\PYQT5_NEW_UI\UI\signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Signup_window(object):
    def setupUi(self, Signup_window):
        Signup_window.setObjectName("Signup_window")
        Signup_window.resize(442, 804)
        Signup_window.setStyleSheet("background-color: rgba(254, 254, 254, 1);")
        self.centralwidget = QtWidgets.QWidget(Signup_window)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(30, 40, 381, 51))
        self.title.setStyleSheet("color: rgba(22, 25, 50, 1);\n"
"font-size: 28pt;\n"
"background-color: transparent;")
        self.title.setObjectName("title")
        self.first_name_label = QtWidgets.QLabel(self.centralwidget)
        self.first_name_label.setGeometry(QtCore.QRect(50, 140, 101, 31))
        self.first_name_label.setStyleSheet("font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);\n"
"background-color: transparent;")
        self.first_name_label.setObjectName("first_name_label")
        self.first_name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.first_name_input.setGeometry(QtCore.QRect(50, 180, 331, 41))
        self.first_name_input.setStyleSheet("border-radius: 20px;\n"
"background-color:rgba(240, 240, 240, 1);\n"
"\n"
"font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);\n"
"\n"
"padding: 5px 10px;")
        self.first_name_input.setObjectName("first_name_input")
        self.last_name_label = QtWidgets.QLabel(self.centralwidget)
        self.last_name_label.setGeometry(QtCore.QRect(50, 250, 101, 31))
        self.last_name_label.setStyleSheet("font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);\n"
"background-color: transparent;")
        self.last_name_label.setObjectName("last_name_label")
        self.last_name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.last_name_input.setGeometry(QtCore.QRect(50, 300, 331, 41))
        self.last_name_input.setStyleSheet("border-radius: 20px;\n"
"background-color:rgba(240, 240, 240, 1);\n"
"\n"
"font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);\n"
"\n"
"padding: 5px 10px;")
        self.last_name_input.setObjectName("last_name_input")
        self.signup_button = QtWidgets.QPushButton(self.centralwidget)
        self.signup_button.setEnabled(True)
        self.signup_button.setGeometry(QtCore.QRect(50, 610, 331, 71))
        self.signup_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #f20089, stop:0.5 #b100e8, stop:1 #6a00f4);\n"
"\n"
"border-radius: 20px;\n"
"font-size: 20px;\n"
"color: rgba(254, 254, 254, 1);\n"
"margin-top: 15px;\n"
"margin-bottom: 15px;")
        self.signup_button.setObjectName("signup_button")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(80, 720, 261, 51))
        self.login_button.setStyleSheet("font-size:10pt;\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #f20089, stop:0.5 #b100e8, stop:1 #6a00f4);\n"
"text-decoration: underline;\n"
"background: transparent\n"
"\n"
"")
        self.login_button.setObjectName("login_button")
        self.email_input = QtWidgets.QLineEdit(self.centralwidget)
        self.email_input.setGeometry(QtCore.QRect(50, 410, 331, 41))
        self.email_input.setStyleSheet("border-radius: 20px;\n"
"background-color:rgba(240, 240, 240, 1);\n"
"\n"
"font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);\n"
"\n"
"padding: 5px 10px;")
        self.email_input.setObjectName("email_input")
        self.email_label = QtWidgets.QLabel(self.centralwidget)
        self.email_label.setGeometry(QtCore.QRect(50, 370, 51, 31))
        self.email_label.setStyleSheet("font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);\n"
"background-color: transparent;")
        self.email_label.setObjectName("email_label")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(50, 530, 331, 41))
        self.password_input.setStyleSheet("border-radius: 20px;\n"
"background-color:rgba(240, 240, 240, 1);\n"
"\n"
"font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);\n"
"\n"
"padding: 5px 10px;")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(50, 480, 91, 31))
        self.password_label.setStyleSheet("font-size:15pt;\n"
"color: rgba(22, 25, 50, 1);\n"
"background-color: transparent;")
        self.password_label.setObjectName("password_label")
        Signup_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Signup_window)
        self.statusbar.setAutoFillBackground(False)
        self.statusbar.setStyleSheet("")
        self.statusbar.setObjectName("statusbar")
        Signup_window.setStatusBar(self.statusbar)
        self.title.setBuddy(self.title)

        self.retranslateUi(Signup_window)
        QtCore.QMetaObject.connectSlotsByName(Signup_window)
        Signup_window.setTabOrder(self.first_name_input, self.last_name_input)
        Signup_window.setTabOrder(self.last_name_input, self.email_input)
        Signup_window.setTabOrder(self.email_input, self.password_input)
        Signup_window.setTabOrder(self.password_input, self.signup_button)
        Signup_window.setTabOrder(self.signup_button, self.login_button)

    def retranslateUi(self, Signup_window):
        _translate = QtCore.QCoreApplication.translate
        Signup_window.setWindowTitle(_translate("Signup_window", "MainWindow"))
        self.title.setText(_translate("Signup_window", "Sign up to start trading"))
        self.first_name_label.setText(_translate("Signup_window", "First name"))
        self.last_name_label.setText(_translate("Signup_window", "Last name"))
        self.signup_button.setText(_translate("Signup_window", "Sign up"))
        self.login_button.setText(_translate("Signup_window", "Already have an account? Log in here"))
        self.email_label.setText(_translate("Signup_window", "Email"))
        self.password_label.setText(_translate("Signup_window", "password"))
