# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\eliran\Desktop\python\PYQT5_NEW_UI\UI\signup_success_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Signuo_success_popup(object):
    def setupUi(self, Signuo_success_popup):
        Signuo_success_popup.setObjectName("Signuo_success_popup")
        Signuo_success_popup.resize(587, 237)
        Signuo_success_popup.setStyleSheet("background-color: rgb(254, 254, 254);")
        self.label = QtWidgets.QLabel(Signuo_success_popup)
        self.label.setGeometry(QtCore.QRect(120, 40, 351, 51))
        self.label.setStyleSheet("background-color: transparent;\n"
"color: rgba(22, 25, 50, 1);\n"
"font-size: 28pt;")
        self.label.setObjectName("label")
        self.login_button = QtWidgets.QPushButton(Signuo_success_popup)
        self.login_button.setEnabled(True)
        self.login_button.setGeometry(QtCore.QRect(130, 130, 331, 71))
        self.login_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #f20089, stop:0.5 #b100e8, stop:1 #6a00f4);\n"
"\n"
"border-radius: 20px;\n"
"font-size: 20px;\n"
"color: rgba(254, 254, 254, 1);\n"
"margin-top: 15px;\n"
"margin-bottom: 15px;")
        self.login_button.setObjectName("login_button")

        self.retranslateUi(Signuo_success_popup)
        QtCore.QMetaObject.connectSlotsByName(Signuo_success_popup)

    def retranslateUi(self, Signuo_success_popup):
        _translate = QtCore.QCoreApplication.translate
        Signuo_success_popup.setWindowTitle(_translate("Signuo_success_popup", "Form"))
        self.label.setText(_translate("Signuo_success_popup", "Signed up succesfuly!"))
        self.login_button.setText(_translate("Signuo_success_popup", "Log in now"))
